services:
  appdb:
    image: "mongodb/mongodb-enterprise-server:${APPDB_VERSION}"
    container_name: appdb
    restart: always
    ports:
      - "${APPDB_MAPPING_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${ROOT_PWD}"
    volumes:
      - ${APPDB_DBPATH}:/data/db
    networks:
      - opsmanager
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
  opsmanager:
    image: "${NAMESPACE}/ops-manager:${OM_VERSION}"
    restart: always
    ports:
      - "${OM_MAPPING_PORT}:8080"
    environment:
      ROOT_USER: "${ROOT_USER}"
      ROOT_PWD: "${ROOT_PWD}"
    volumes:
      - ${RELEASES}:/mongodb-mms/mongodb-releases
      - ${OM_LOGS}:/mongodb-mms/logs
    networks:
      - opsmanager
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G
  backup-daemon:
    image: "${NAMESPACE}/backup-daemon:${OM_VERSION}"
    restart: always
    ports:
      - "27700-27719:27700-27719"
      - "25999:25999"
    volumes:
      - ${RELEASES}:/mongodb-mms/mongodb-releases
      - ${BACKUPD_LOGS}:/mongodb-mms/logs
      - ${OM_SNAPSHOTS}:/snapshots
      - ${OM_HEAD_DB}:/headDB
    networks:
      - opsmanager
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
networks:
  opsmanager:
    driver: bridge
