services:
  mongo:
    image: "${NAMESPACE}/mongodb:${OM_VERSION}"
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/data/log
    ports:
      - "27017"
    restart: always
    networks:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
networks:
  mongo:
    driver: bridge
volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ${MONGO_DBPATH}
      o: bind
  mongo_logs:
    driver: local
    driver_opts:
      type: none
      device: ${MONGO_LOGPATH}
      o: bind