version: "3.8"
services:
  mongo:
    image: "${DOCKER_USERNAME}/mongo"
    ports:
      - "27017"
    restart: always
    networks:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
networks:
  mongo:
    driver: bridge