services:
  mongodb:
    image: "${NAMESPACE}/mongodb:${OM_VERSION}"
    hostname: "mongo_${PROJECT_IDX}_${IDX}"
    volumes:
      - ${MONGO_DBPATH}/mongo_${PROJECT_IDX}_${IDX}:/data/db
      - ${MONGO_LOGPATH}/mongo_${PROJECT_IDX}_${IDX}:/data/log
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      OM_URL: "http://host.docker.internal:${OM_MAPPING_PORT}"
      PROJECT_ID: "${PROJECT_ID}"
      AGENT_API_KEY: "${AGENT_API_KEY}"
    restart: always
    networks:
      - docker_mongodb
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
networks:
  docker_mongodb:
    external: true
    name: docker_mongodb