#!/bin/bash
source ./config.sh

start() {
    docker-compose up --scale mongo=$INSTANCES -d
}

stop() {
    docker-compose down
}

restart() {
  stop
  start
}

if [ ! -z "$2" ]; then
    INSTANCES=$2
fi
echo "Starting $INSTANCES instances."
case "$1" in
    start|stop|restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
        ;;
esac