#!/bin/bash
source ./config.sh

start() {
    for IDX in $(seq 1 $INSTANCES); do
        export IDX
        docker-compose up --scale mongo=$IDX --no-recreate -d
    done
}

stop() {
    export IDX=0
    docker-compose down -t 5
}

restart() {
  stop
  start
}

if [ ! -z "$2" ]; then
    INSTANCES=$2
fi
echo "Starting $INSTANCES instances."
case "$1" in
    start|stop|restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
        ;;
esac